/**
 * Plano de contas padrão (receita + despesa).
 * Baseado em modelo DRE brasileiro simplificado — pode ser expandido
 * com importação do xls do Tiny via categoria import endpoint.
 */
export interface CategoriaSeed {
  codigo: string;
  nome: string;
  nivel: 1 | 2 | 3;
  path: string;
  parent_codigo: string | null;
  tipo: 'receita' | 'despesa' | 'transferencia';
  natureza?: 'operacional' | 'nao_operacional' | 'financeira' | 'tributaria';
  dre_grupo?: string;
}

export const CATEGORIAS_SEED: CategoriaSeed[] = [
  // ===================== RECEITAS =====================
  {
    codigo: '1',
    nome: 'Receitas',
    nivel: 1,
    path: '1',
    parent_codigo: null,
    tipo: 'receita',
    natureza: 'operacional',
    dre_grupo: 'Receita Bruta',
  },
  {
    codigo: '1.01',
    nome: 'Receita de Vendas',
    nivel: 2,
    path: '1.01',
    parent_codigo: '1',
    tipo: 'receita',
    natureza: 'operacional',
    dre_grupo: 'Receita Bruta',
  },
  {
    codigo: '1.01.001',
    nome: 'Venda de Produtos',
    nivel: 3,
    path: '1.01.001',
    parent_codigo: '1.01',
    tipo: 'receita',
    natureza: 'operacional',
    dre_grupo: 'Receita Bruta',
  },
  {
    codigo: '1.01.002',
    nome: 'Venda de Serviços',
    nivel: 3,
    path: '1.01.002',
    parent_codigo: '1.01',
    tipo: 'receita',
    natureza: 'operacional',
    dre_grupo: 'Receita Bruta',
  },
  {
    codigo: '1.02',
    nome: 'Receitas Financeiras',
    nivel: 2,
    path: '1.02',
    parent_codigo: '1',
    tipo: 'receita',
    natureza: 'financeira',
    dre_grupo: 'Receitas Financeiras',
  },
  {
    codigo: '1.02.001',
    nome: 'Rendimentos de Aplicações',
    nivel: 3,
    path: '1.02.001',
    parent_codigo: '1.02',
    tipo: 'receita',
    natureza: 'financeira',
    dre_grupo: 'Receitas Financeiras',
  },
  {
    codigo: '1.02.002',
    nome: 'Juros Recebidos',
    nivel: 3,
    path: '1.02.002',
    parent_codigo: '1.02',
    tipo: 'receita',
    natureza: 'financeira',
    dre_grupo: 'Receitas Financeiras',
  },
  {
    codigo: '1.03',
    nome: 'Outras Receitas',
    nivel: 2,
    path: '1.03',
    parent_codigo: '1',
    tipo: 'receita',
    natureza: 'nao_operacional',
    dre_grupo: 'Outras Receitas',
  },

  // ===================== DESPESAS =====================
  {
    codigo: '2',
    nome: 'Despesas',
    nivel: 1,
    path: '2',
    parent_codigo: null,
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Operacionais',
  },

  // CMV
  {
    codigo: '2.01',
    nome: 'Custo da Mercadoria Vendida',
    nivel: 2,
    path: '2.01',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'CMV',
  },
  {
    codigo: '2.01.001',
    nome: 'Compra de Mercadorias',
    nivel: 3,
    path: '2.01.001',
    parent_codigo: '2.01',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'CMV',
  },
  {
    codigo: '2.01.002',
    nome: 'Matéria-Prima',
    nivel: 3,
    path: '2.01.002',
    parent_codigo: '2.01',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'CMV',
  },
  {
    codigo: '2.01.003',
    nome: 'Insumos de Produção (Neon LED)',
    nivel: 3,
    path: '2.01.003',
    parent_codigo: '2.01',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'CMV',
  },
  {
    codigo: '2.01.004',
    nome: 'Frete sobre Compras',
    nivel: 3,
    path: '2.01.004',
    parent_codigo: '2.01',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'CMV',
  },

  // Despesas Comerciais
  {
    codigo: '2.02',
    nome: 'Despesas Comerciais',
    nivel: 2,
    path: '2.02',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },
  {
    codigo: '2.02.001',
    nome: 'MDO Comercial - AtacadoNeon',
    nivel: 3,
    path: '2.02.001',
    parent_codigo: '2.02',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },
  {
    codigo: '2.02.002',
    nome: 'Comissões de Vendas',
    nivel: 3,
    path: '2.02.002',
    parent_codigo: '2.02',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },
  {
    codigo: '2.02.003',
    nome: 'Marketing e Publicidade',
    nivel: 3,
    path: '2.02.003',
    parent_codigo: '2.02',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },
  {
    codigo: '2.02.004',
    nome: 'Meta Ads / Mídia Paga',
    nivel: 3,
    path: '2.02.004',
    parent_codigo: '2.02',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },
  {
    codigo: '2.02.005',
    nome: 'Frete sobre Vendas',
    nivel: 3,
    path: '2.02.005',
    parent_codigo: '2.02',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Comerciais',
  },

  // Despesas Administrativas
  {
    codigo: '2.03',
    nome: 'Despesas Administrativas',
    nivel: 2,
    path: '2.03',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.001',
    nome: 'Salários e Encargos',
    nivel: 3,
    path: '2.03.001',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.002',
    nome: 'Pró-labore',
    nivel: 3,
    path: '2.03.002',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.003',
    nome: 'Aluguel',
    nivel: 3,
    path: '2.03.003',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.004',
    nome: 'Energia Elétrica',
    nivel: 3,
    path: '2.03.004',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.005',
    nome: 'Água e Esgoto',
    nivel: 3,
    path: '2.03.005',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.006',
    nome: 'Telefone e Internet',
    nivel: 3,
    path: '2.03.006',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.007',
    nome: 'Contabilidade',
    nivel: 3,
    path: '2.03.007',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },
  {
    codigo: '2.03.008',
    nome: 'Material de Escritório',
    nivel: 3,
    path: '2.03.008',
    parent_codigo: '2.03',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Administrativas',
  },

  // Despesas com Tecnologia
  {
    codigo: '2.04',
    nome: 'Despesas com Tecnologia',
    nivel: 2,
    path: '2.04',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Operacionais',
  },
  {
    codigo: '2.04.001',
    nome: 'SaaS e Softwares',
    nivel: 3,
    path: '2.04.001',
    parent_codigo: '2.04',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Operacionais',
  },
  {
    codigo: '2.04.002',
    nome: 'Hospedagem e Servidores',
    nivel: 3,
    path: '2.04.002',
    parent_codigo: '2.04',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Operacionais',
  },
  {
    codigo: '2.04.003',
    nome: 'Domínios',
    nivel: 3,
    path: '2.04.003',
    parent_codigo: '2.04',
    tipo: 'despesa',
    natureza: 'operacional',
    dre_grupo: 'Despesas Operacionais',
  },

  // Despesas Financeiras
  {
    codigo: '2.05',
    nome: 'Despesas Financeiras',
    nivel: 2,
    path: '2.05',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'financeira',
    dre_grupo: 'Despesas Financeiras',
  },
  {
    codigo: '2.05.001',
    nome: 'Juros Pagos',
    nivel: 3,
    path: '2.05.001',
    parent_codigo: '2.05',
    tipo: 'despesa',
    natureza: 'financeira',
    dre_grupo: 'Despesas Financeiras',
  },
  {
    codigo: '2.05.002',
    nome: 'Tarifas Bancárias',
    nivel: 3,
    path: '2.05.002',
    parent_codigo: '2.05',
    tipo: 'despesa',
    natureza: 'financeira',
    dre_grupo: 'Despesas Financeiras',
  },
  {
    codigo: '2.05.003',
    nome: 'IOF',
    nivel: 3,
    path: '2.05.003',
    parent_codigo: '2.05',
    tipo: 'despesa',
    natureza: 'financeira',
    dre_grupo: 'Despesas Financeiras',
  },
  {
    codigo: '2.05.004',
    nome: 'Taxa Gateway (Pagar.me, AppMax)',
    nivel: 3,
    path: '2.05.004',
    parent_codigo: '2.05',
    tipo: 'despesa',
    natureza: 'financeira',
    dre_grupo: 'Despesas Financeiras',
  },

  // Tributos
  {
    codigo: '2.06',
    nome: 'Tributos',
    nivel: 2,
    path: '2.06',
    parent_codigo: '2',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },
  {
    codigo: '2.06.001',
    nome: 'Simples Nacional / DAS',
    nivel: 3,
    path: '2.06.001',
    parent_codigo: '2.06',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },
  {
    codigo: '2.06.002',
    nome: 'ICMS',
    nivel: 3,
    path: '2.06.002',
    parent_codigo: '2.06',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },
  {
    codigo: '2.06.003',
    nome: 'ISS',
    nivel: 3,
    path: '2.06.003',
    parent_codigo: '2.06',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },
  {
    codigo: '2.06.004',
    nome: 'INSS',
    nivel: 3,
    path: '2.06.004',
    parent_codigo: '2.06',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },
  {
    codigo: '2.06.005',
    nome: 'FGTS',
    nivel: 3,
    path: '2.06.005',
    parent_codigo: '2.06',
    tipo: 'despesa',
    natureza: 'tributaria',
    dre_grupo: 'Tributos',
  },

  // ===================== TRANSFERÊNCIAS =====================
  {
    codigo: '3',
    nome: 'Transferências entre Contas',
    nivel: 1,
    path: '3',
    parent_codigo: null,
    tipo: 'transferencia',
  },
  {
    codigo: '3.01',
    nome: 'Transferência Intercompany',
    nivel: 2,
    path: '3.01',
    parent_codigo: '3',
    tipo: 'transferencia',
  },
  {
    codigo: '3.02',
    nome: 'Transferência Mesma Empresa',
    nivel: 2,
    path: '3.02',
    parent_codigo: '3',
    tipo: 'transferencia',
  },
];
